
#FOR MOE INFOS, CHECK OUT THE   - organisers.yml file 
# Site settings
title: é’»æˆ’ðŸ’ 
#What is the name of the events or talks you would like to host? (Example Brownbags, Talks, Lighting Talks)
event_label: Events

description: > # "
  Daily Record

baseurl: "" # the subpath of your site, e.g. /blog
url: "http://blog.9dic.com" # the base hostname & protocol for your site

#These settings might be able to go?
author: Asingers 
twitter_username: yourtwitter
github_username:  yourgithub
company_name: yourname

# Build settings
markdown: kramdown

#Have to show future posts for future events.
future: true

permalink: /event/:title.html

#change your port on localhost
port: 8000


